<a href="https://colab.research.google.com/github/mmugilamugila-art/Data-Analytics-using-python-project-/blob/main/day_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

numpy arr

In [ ]:
import numpy as np
marks = np.array([60,45,74,67])
print(marks)

[60 45 74 67]


In [ ]:
import numpy as np
Students = np.array([
    [70,46],
    [60,48],
     [78,90],
    [50,80]
])
print(Students)


[[70 46]
 [60 48]
 [78 90]
 [50 80]]


In [ ]:
import numpy as np
num = np.array([
    [[3,4],[5,6]],[[5,7],[8,7]],
    [[4,2],[3,1]]
])
print(num)

[[[3 4]
  [5 6]]

 [[5 7]
  [8 7]]

 [[4 2]
  [3 1]]]


In [1]:
import numpy as np
arr = np.zeros((3,4))
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


Array Operation

In [ ]:
import numpy as np
a = np.array([1,2,3,4,5])
b = np.array([10,20,30,40,50])

print(a+b)
print(a*b)
print(np.sqrt(a))
print(np.sum(a))
print(np.mean(b))